name = "ProximalBase"
uuid = "0a755509-c5b1-5d6f-9b24-59bcda3c37a3"
author = ["Mladen Kolar <mkolar@chicagobooth.edu>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.2"
